apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: n8n
  namespace: app
spec:
  interval: 2m
  chart:
    spec:
      chart: charts/n8n
      sourceRef:
        kind: GitRepository
        name: n8n
        namespace: app
  valuesFrom:
    - kind: ConfigMap
      name: n8n-helm
      valuesKey: helm-values.yaml
