apiVersion: v1
kind: Secret
metadata:
  name: {{ include "automatisch.fullname" . }}-encryption-keys
  labels:
    {{- include "automatisch.labels" . | nindent 4 }}
data:
  encryption-key: {{ randAscii 14 | b64enc }}
  webhook-secret-key: {{ randAscii 14 | b64enc }}
