{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "automatisch.fullname" . }}
  labels:
    {{- include "automatisch.labels" . | nindent 4 }}
spec:
  rules:
  - host: {{ .Values.ingress.subdomain }}.alexisfougerouse.fr
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: {{ include "automatisch.fullname" . }}
            port:
              number: {{ .Values.service.port }}
{{- end }}
