apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
  namespace: database
spec:
  interval: 4h
  chart:
    spec:
      chart: redis
      sourceRef:
        kind: HelmRepository
        name: ot-helm 
        namespace: redis-ot-system
