apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: automatisch
  namespace: app
spec:
  interval: 2m
  chart:
    spec:
      chart: app/telecaster/automatisch/chart/
      sourceRef:
        kind: GitRepository
        name: automatisch
        namespace: app
  valuesFrom:
    - kind: ConfigMap
      name: automatisch-helm
      valuesKey: helm-values.yaml
