apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: automatisch
  namespace: app
spec:
  interval: 1m
  url: https://github.com/Panderium/infrartcore/tree/main/app/telecaster/automatisch/chart
  ref:
    branch: main
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/app/telecaster/automatisch/chart   