apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis-operator
  namespace: redis-ot-system
spec:
  interval: 4h
  chart:
    spec:
      chart: redis-operator
      sourceRef:
        kind: HelmRepository
        name: ot-helm 
        namespace: redis-ot-system
