apiVersion: v1
kind: ConfigMap
metadata:
  name: metrics-server-helm
  namespace: kube-system
data:
  helm-values.yaml: |
    args: 
      - --kubelet-insecure-tls
    resources:
      requests:
        cpu: 20m
        memory: 50Mi