apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  interval: 4h
  chart:
    spec:
      chart: metrics-server
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: kube-system
  valuesFrom:
    - kind: ConfigMap
      name: metrics-server-helm
      valuesKey: helm-values.yaml
    