apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: database
  namespace: database
spec:
  interval: 4h
  chart:
    spec:
      chart: cluster
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: cnpg-system
  valuesFrom:
    - kind: ConfigMap
      name: database-helm
      valuesKey: helm-values.yaml